#sudo: required
#services:
#  - docker
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest pytest-cov
script:
  - python -m pytest -v --cov=./
after_success:
#  - sh .travis/deploy_dockerhub.sh
  - codecov
